namespace Junction.Queue;

/// <summary>
/// The PostgreSQL objects Junction needs, as idempotent DDL. Applied for you by
/// <see cref="IQueueClient.InitializeAsync"/> when <see cref="QueueOptions.AutoCreateSchema"/> is
/// on; exposed here so you can paste it into a migration instead (or check what a
/// <c>ModelBuilder.AddJunctionModel()</c> migration is expected to produce).
/// </summary>
public static class QueueSchema
{
    /// <summary>Default schema name.</summary>
    public const string DefaultSchema = "junction";

    /// <summary>
    /// Tables and indexes. Notable choices:
    /// <list type="bullet">
    /// <item>
    /// <b>Partial index on claimable rows only</b> (<c>WHERE state = 0</c>): the index the claim walks
    /// is the size of the backlog, not of the table. Leased rows leave it, completed rows never enter
    /// it, so a queue that has processed ten million messages claims as fast as an empty one.
    /// </item>
    /// <item>
    /// <b>No foreign keys</b> on the hot table (<c>queue_id</c> is a value, not a constraint): a queue
    /// row is never deleted while messages reference it, and an FK check would add an index probe and
    /// a parent-row lock to every single enqueue.
    /// </item>
    /// <item>
    /// <b>Payload as <c>bytea</c></b>: opaque to the library, and large payloads go to TOAST instead of
    /// bloating the pages the claim scans.
    /// </item>
    /// </list>
    /// </summary>
    public static string CreateScript(string schema = DefaultSchema) =>
        $"""
         CREATE SCHEMA IF NOT EXISTS {schema};

         CREATE TABLE IF NOT EXISTS {schema}.queues (
             id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
             name        text NOT NULL,
             created_at  timestamptz NOT NULL DEFAULT now()
         );

         CREATE UNIQUE INDEX IF NOT EXISTS ux_queues_name ON {schema}.queues (name);

         CREATE TABLE IF NOT EXISTS {schema}.messages (
             id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
             queue_id          integer NOT NULL,
             state             smallint NOT NULL DEFAULT 0,
             priority          integer NOT NULL DEFAULT 0,
             visible_at        timestamptz NOT NULL DEFAULT now(),
             enqueued_at       timestamptz NOT NULL DEFAULT now(),
             attempts          integer NOT NULL DEFAULT 0,
             max_attempts      integer NOT NULL DEFAULT 5,
             lease_token       uuid,
             lease_expires_at  timestamptz,
             worker_id         text,
             message_type      text NOT NULL,
             payload           bytea NOT NULL,
             headers           jsonb,
             dedup_key         text,
             last_error        text
         );

         -- The claim path, and the only index that has to stay small.
         CREATE INDEX IF NOT EXISTS ix_messages_ready
             ON {schema}.messages (queue_id, priority DESC, visible_at, id)
             WHERE state = 0;

         -- The lease-recovery sweep: only in-flight rows.
         CREATE INDEX IF NOT EXISTS ix_messages_lease
             ON {schema}.messages (lease_expires_at)
             WHERE state = 1;

         -- Producer-side idempotency: one pending message per (queue, dedup key).
         CREATE UNIQUE INDEX IF NOT EXISTS ux_messages_dedup
             ON {schema}.messages (queue_id, dedup_key)
             WHERE dedup_key IS NOT NULL;

         CREATE TABLE IF NOT EXISTS {schema}.dead_letters (
             id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
             message_id    bigint NOT NULL,
             queue_id      integer NOT NULL,
             message_type  text NOT NULL,
             payload       bytea NOT NULL,
             headers       jsonb,
             priority      integer NOT NULL DEFAULT 0,
             attempts      integer NOT NULL,
             max_attempts  integer NOT NULL,
             enqueued_at   timestamptz NOT NULL,
             failed_at     timestamptz NOT NULL DEFAULT now(),
             error         text,
             dedup_key     text
         );

         CREATE INDEX IF NOT EXISTS ix_dead_letters_queue
             ON {schema}.dead_letters (queue_id, failed_at DESC);

         CREATE TABLE IF NOT EXISTS {schema}.completed (
             id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
             message_id    bigint NOT NULL,
             queue_id      integer NOT NULL,
             message_type  text NOT NULL,
             payload       bytea NOT NULL,
             headers       jsonb,
             attempts      integer NOT NULL,
             enqueued_at   timestamptz NOT NULL,
             completed_at  timestamptz NOT NULL DEFAULT now(),
             worker_id     text
         );

         CREATE INDEX IF NOT EXISTS ix_completed_at ON {schema}.completed (completed_at);
         """;

    /// <summary>
    /// The index the starvation-free claim needs: claimable rows ordered by how long they have been
    /// claimable, ignoring priority. Applied by <see cref="IQueueClient.InitializeAsync"/> only when
    /// <see cref="QueueOptions.StarvationThreshold"/> is set, because a second index on the hot table
    /// doubles its index maintenance on every insert and every claim — a cost nobody should pay for a
    /// feature they have not asked for.
    /// <para>
    /// Partial like the others: it indexes claimable rows only, so it stays the size of the backlog.
    /// </para>
    /// </summary>
    public static string StarvationIndexScript(string schema = DefaultSchema) =>
        $"""
         CREATE INDEX IF NOT EXISTS ix_messages_age
             ON {schema}.messages (queue_id, visible_at, id)
             WHERE state = 0;
         """;

    /// <summary>
    /// Storage tuning for the hot table. A queue table is the most update- and delete-heavy table in
    /// a system: every message is inserted, updated once per attempt and then removed, so dead tuples
    /// are produced at exactly the throughput rate. With stock autovacuum settings (vacuum at 20% of
    /// the table) a busy queue accumulates dead tuples faster than they are reclaimed, and claim
    /// latency climbs with the bloat — the classic "our Postgres queue got slow" failure.
    /// <list type="bullet">
    /// <item><c>fillfactor = 85</c> leaves room on each page for the lease update to stay in-place (HOT), avoiding index churn.</item>
    /// <item><c>autovacuum_vacuum_scale_factor = 0.02</c> + a low threshold vacuum this table continuously instead of in rare, painful sweeps.</item>
    /// <item><c>autovacuum_vacuum_cost_delay = 0</c> lets that vacuum run at full speed; it is a small table by design.</item>
    /// </list>
    /// </summary>
    public static string TuningScript(string schema = DefaultSchema) =>
        $"""
         ALTER TABLE {schema}.messages SET (
             fillfactor = 85,
             autovacuum_vacuum_scale_factor = 0.02,
             autovacuum_vacuum_threshold = 100,
             autovacuum_vacuum_cost_delay = 0,
             autovacuum_analyze_scale_factor = 0.05
         );
         """;
}
