namespace Junction.Stream;

/// <summary>
/// The PostgreSQL objects the Stream module needs, as idempotent DDL. Applied for you by
/// <see cref="IStreamClient.InitializeAsync"/> when <see cref="StreamOptions.AutoCreateSchema"/> is
/// on; exposed here so you can paste it into a migration instead.
/// </summary>
public static class StreamSchema
{
    /// <summary>
    /// Schema holding the Stream tables. Fixed, unlike Queue's <c>QueueOptions.Schema</c> — see
    /// <see cref="JunctionDbContext.Schema"/>.
    /// </summary>
    public const string DefaultSchema = JunctionDbContext.Schema;

    public static string CreateScript() =>
        $"""
         CREATE SCHEMA IF NOT EXISTS {DefaultSchema};

         CREATE TABLE IF NOT EXISTS {DefaultSchema}.streams (
             id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
             name        text NOT NULL,
             next_seq    bigint NOT NULL DEFAULT 0,
             created_at  timestamptz NOT NULL DEFAULT now()
         );

         CREATE UNIQUE INDEX IF NOT EXISTS ux_streams_name ON {DefaultSchema}.streams (name);

         CREATE TABLE IF NOT EXISTS {DefaultSchema}.stream_events (
             id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
             stream_id   bigint NOT NULL,
             seq         bigint NOT NULL,
             event_key   text,
             event_type  text NOT NULL,
             payload     bytea NOT NULL,
             headers     jsonb,
             created_at  timestamptz NOT NULL DEFAULT now()
         );

         -- Primary (and only) access path: range scan by (stream, seq) for a consumer poll.
         CREATE UNIQUE INDEX IF NOT EXISTS ux_events_stream_seq
             ON {DefaultSchema}.stream_events (stream_id, seq);

         CREATE TABLE IF NOT EXISTS {DefaultSchema}.consumer_cursors (
             id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
             stream_id      bigint NOT NULL,
             consumer_name  text NOT NULL,
             position       bigint NOT NULL DEFAULT 0,
             updated_at     timestamptz NOT NULL DEFAULT now()
         );

         CREATE UNIQUE INDEX IF NOT EXISTS ux_cursor_stream_consumer
             ON {DefaultSchema}.consumer_cursors (stream_id, consumer_name);
         """;
}
